name: angelheart
favicon: null
layout_spectrum: 0.5067338396329433
typography_spectrum: 0.58551408466883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8892875260207802
  lightness: 0.9196269405074418
  saturation: 0.9337431958410889
  rhythmicContrast: 0.4243594326544553
purpose: []
